import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import { SessionProvider } from '@components/SessionProvider'
import Login from '@components/Login'
import ClientProvider from '@components/ClientProvider'
import Sidebar from '@components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ?(
            <Login />
          ):(
            <div className='flex'>
            <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[16.2rem]'>
            <Sidebar />
            </div>
              <ClientProvider />
            <div className='bg-[#343541] flex-1'>{children}</div>
          </div>
          )}
        </SessionProvider>
        </body>
    </html>
  )
}
